<?php
/**
 * Implements hook_secure_permissions().
 *
 * Adding permissions
 */
function cu_connect_bundle_secure_permissions($role) {
  $permissions = array(
    'administrator' => array(
      'create cuod_course content',
      'edit own cuod_course content',
      'edit any cuod_course content',
      'delete own cuod_course content',
      'delete any cuod_course content',
      'create cuod_degreeprogram content',
      'edit own cuod_degreeprogram content',
      'edit any cuod_degreeprogram content',
      'delete own cuod_degreeprogram content',
      'delete any cuod_degreeprogram content',
    ),
    'anonymous user' => array(
    ),
    'authenticated user' => array(
    ),
    'content_editor' => array(
    ),
    'developer' => array(
      'administer salesforce webform',
      'create cuod_course content',
      'edit own cuod_course content',
      'edit any cuod_course content',
      'delete own cuod_course content',
      'delete any cuod_course content',
      'create cuod_degreeprogram content',
      'edit own cuod_degreeprogram content',
      'edit any cuod_degreeprogram content',
      'delete own cuod_degreeprogram content',
      'delete any cuod_degreeprogram content',
    ),
    'edit_my_content' => array(
    ),
    'site_owner' => array(
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

