<?php

/*
 * Implements hook_secure_permissions
 *
 * Adding permissions for video reveal bean
 */
function cu_publications_bundle_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
    ),
    'authenticated user' => array(
    ),
    'administrator' => array(
      'create issue content',
      'delete any issue content',
      'delete own issue content',
      'edit any issue content',
      'edit own issue content',
      'view any issue content',
    ),
    'content_editor' => array(
      'create issue content',
      'delete any issue content',
      'delete own issue content',
      'edit any issue content',
      'edit own issue content',
      'view any issue content',
    ),
    'developer' => array(
      'create issue content',
      'delete any issue content',
      'delete own issue content',
      'edit any issue content',
      'edit own issue content',
      'view any issue content',
    ),
    'site_owner' => array(
      'create issue content',
      'delete any issue content',
      'delete own issue content',
      'edit any issue content',
      'edit own issue content',
      'view any issue content',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_menu_alter().
 * TEMP - revert this back to allow anonymous users to access
 */
function cu_publications_bundle_menu_alter(&$items) {
  // Restrict access to taxonomy term pages to authenticated users.
  $items['taxonomy/term/%taxonomy_term']['access callback'] = TRUE;
  // Remove /node page from being accessed.
  $items['node']['page callback'] = 'taxonomy_term_page';
}
