<?php
/**
 * @file
 * Code for the Find a Story feature.
 */

include_once 'cu_find_a_story.features.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function cu_find_a_story_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'cu_find_a_story');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'cu_find_a_story', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('cu_find_a_story');
  foreach ($hooks as $h) {
    if (isset($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
    }
  }
}
